apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-app-ingress
  namespace: ml-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/wallarm-mode: "monitoring"
    nginx.ingress.kubernetes.io/wallarm-application: "14"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ml-app.myapp.com
      secretName: ml-app-tls
  rules:
    - host: ml-app.myapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-app-service
                port:
                  number: 8000
