name: ml-api
app: ml-api
namespace: ml-app
replicaCount: 2

image:
  repository: europe-west2-docker.pkg.dev/micro-answer-423900-n6/finden/ml-app
  tag: "1.0.0"

containerPort: 8000

env:
  MODEL_VERSION: "1.0.0"
  GCS_BUCKET: "ml-models-iris"

secretName: gcp-sa-key

service:
  name: ml-api-service
  type: LoadBalancer
  port: 80

probes:
  path: /health
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 20

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"