replicaCount: 2

image:
  repository: europe-west2-docker.pkg.dev/micro-answer-423900-n6/finden/ml-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  MODEL_VERSION: "1.0.0"
  GCS_BUCKET: "ml-models-iris"
  GOOGLE_APPLICATION_CREDENTIALS: "/var/secrets/gcp/key.json"

gcpServiceAccountSecret: gcp-sa-key

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
