apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: download-model
          image: "google/cloud-sdk:alpine"
          command: ["/bin/sh", "-c", "gcloud auth activate-service-account --key-file=/var/secrets/gcp/key.json && gsutil cp gs://{{ .Values.env.GCS_BUCKET }}/{{ .Values.env.MODEL_VERSION }}/model_pipeline.joblib /models/ && ls -l /models"]
          volumeMounts:
            - name: model-volume
              mountPath: /models
            - name: gcp-sa-key
              mountPath: /var/secrets/gcp
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/gcp/key.json"
      containers:
        - name: {{ .Values.app }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_VERSION
              value: "{{ .Values.env.MODEL_VERSION }}"
            - name: GCS_BUCKET
              value: "{{ .Values.env.GCS_BUCKET }}"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "{{ .Values.env.GOOGLE_APPLICATION_CREDENTIALS }}"
          volumeMounts:
            - name: model-volume
              mountPath: /models          
            - name: gcp-sa-key
              mountPath: /var/secrets/gcp
              readOnly: true
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: model-volume
          emptyDir: {}      
        - name: gcp-sa-key
          secret:
            secretName: {{ .Values.gcpServiceAccountSecret }}
