apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 15
          type: Percent
          value: 100
      selectPolicy: Min
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
        - periodSeconds: 15
          type: Percent
          value: 100
        - periodSeconds: 15
          type: Pods
          value: 4
      selectPolicy: Max
      stabilizationWindowSeconds: 60
  maxReplicas: 3
  minReplicas: 3
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: {{ .Values.app }}
        target:
          type: Utilization
          averageUtilization: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-api