apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-api.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ml-api.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
