name: MLAPP - Build and Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west2
  REPO_NAME: finden
  IMAGE_NAME: py_drive_connector
  IMAGE: europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/finden/py_drive_connector

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set Application Default Credentials for GCP SDK
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcloud.json" >> $GITHUB_ENV

      - name: Write credentials to file
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > ${{ github.workspace }}/gcloud.json

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Set PYTHONPATH for pytest
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run unit tests
        run: pytest tests/unit

      - name: Run integration tests
        run: pytest tests/integration

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA